name: bookmi_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^6.0.3
  socket_io_client: ^2.0.3+1
  table_calendar: ^3.1.2
  intl: ^0.19.0
  image_picker: ^0.8.4+3
  mime: ^1.0.0
  http_parser: ^4.0.0
  universal_html: ^2.0.6
  cupertino_icons: ^1.0.6
  path: ^1.8.0
  carousel_slider: ^4.0.0
  shared_preferences: ^2.0.9
  lottie: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Bookmi_logo.png
    - assets/images/istockphoto-1365649825-612x612.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 700
